### ISSUE TITLE
Push/Pop导航栏背景颜色变化进度不准确

### ISSUE THREAD

**Issue by GreenHero** [wangrui460/WRNavigationBar#10]
CATransaction setAnimationDuration:wrPopDuration];
[CATransaction begin];
NSArray<UIViewController *> *vcs = [self wr_popToViewController:viewController animated:animated];
[CATransaction commit];

这个代码[CATransaction setAnimationDuration:wrPopDuration];设置没有效果，
因为后面 [self wr_popToViewController:viewController animated:animated];调用了系统的方法，把你之前的commit覆盖掉，这个pop的动画时间好像永远都是0.5秒，wrPopDisplayCount打印出来一直是31
在模拟器上设置设置慢速动画可以看出，导航栏颜色变化接近突变。

**Comment by wangrui460** [comment]
因为系统没有提供push和pop的progress，所以我只能用这种方法来解决~

**Comment by GreenHero** [comment]
根据wrPopDisplayCount，知道整个pop的动画应该是0.5秒，改一下wrPopDuration就能解决

**Comment by wangrui460** [comment]
对啊，所以需要自己模拟一个进度出来
