### ISSUE TITLE
在项目中引用了其他第三方里自带的导航控制器,会导致他的导航栏颜色默认为白色,即使设置颜色也不行

### ISSUE THREAD

**Issue by losedMemory** [wangrui460/WRNavigationBar#100]
例如导入TZImagePickerController ,该怎样去解决与其他第三方的冲突?希望作者能给个解决方法

**Comment by wangrui460** [comment]
更新了1.2.0版本，加入了 “黑名单” 功能，可查看 Demo

**Comment by 1277393484** [comment]
demo中第一次进去TZImagePickerController导航栏颜色没问题，返回后 ， 再次进去就变成全局蓝色了

**Comment by MrCaiWH** [comment]
@1277393484 兄弟，我也碰到这个问题了，解决了吗
