### ISSUE TITLE
No visible @interface for 'NavigationController' declares the selector 'wr_setDefaultNavBarBarTintColor:'

### ISSUE THREAD

**Issue by alexyubin** [wangrui460/WRNavigationBar#103]
xcode9.0 ,
无论是用cocoapods 安装, 还是直接拖文件进去工程里面, 都会出现这些错误

No visible @interface for 'NavigationController' declares the selector 'wr_setDefaultNavBarShadowImageHidden:'

No known class method for selector 'wr_setDefaultNavBarBarTintColor:'

**Comment by wangrui460** [comment]
是否解决了？
