### ISSUE TITLE
黑名单失效

### ISSUE THREAD

**Issue by mrxiaozuo** [wangrui460/WRNavigationBar#104]
1.2.0添加的黑名单如果是VC  present出来的TZImagePickerController导航栏颜色是正常的，如果是在UITableViewCell里面用self.viewController 去present TZImagePickerController导航栏依然是白色的

**Comment by wangrui460** [comment]
不是很明白你的意思，能不能给个 Demo

**Comment by mrxiaozuo** [comment]
https://github.com/mrxiaozuo/teseDome
这是dome地址

**Comment by JamWangJam** [comment]
我 想问一下 你为什么在viewwillappear 里面 判断 黑名单里面的VC 去更新navagation  不是黑名单吗?

**Comment by luo-h** [comment]
我也是这个问题，在cell中present到TZImagePickerController导航栏是白色，并且item的颜色也是白色

**Comment by 18220868151** [comment]
我去,还真是一楼说的那样
1、如果是cell或者cell的某个SubView响应的点击事件,然后present出来的TZImagePickerController导航栏就是白色的,WRNavigationBar设置了黑名单也没用。
2、如果这个点击事件没有在cell上面,则一切正常。比如在VC中touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event 去present出来的TZImagePickerController就完全正常,WRNavigationBar设置了黑名单就是有效的,好奇怪
