### ISSUE TITLE
iOS 11，Xcode 9下的问题

### ISSUE THREAD

**Issue by huanglins** [wangrui460/WRNavigationBar#11]
![2017-06-24 1 24 48](https://user-images.githubusercontent.com/10528244/27493310-fa063260-587b-11e7-9fe0-ec3636a13095.png)
还有一些其他问题。

**Comment by ws1227** [comment]
这个 是xcode9  iOS11 通病

**Comment by lewis180777** [comment]
这个问题怎么解决，位置错乱还容易解决，关键是自定义的导航栏就没有那个效果了

**Comment by wangrui460** [comment]
我用iOS11最新版本烧了一下，并没有出现你说的问题，如果你用的是模拟器，请用真机测试，下面是真机效果
![edfdbdc35f3c15d63d5149eae6065714](https://user-images.githubusercontent.com/11909313/29159704-24c5d1d2-7de2-11e7-993e-22bd3fab44e0.png)

**Comment by xinge1** [comment]
使用xcode9 beat6，运行ios11设备时跟楼主出现一样的问题。而且自定义导航栏设置图片无效，
wr_setNavBarBackgroundImage这个方法设置的图片变成透明的了

**Comment by 276523923** [comment]
iPhoneX模拟器出问题了。。位置都不对了。。

**Comment by JianRuHong** [comment]
在iPhone X上, 导航栏设置透明是没有任何效果的, 是白色的

**Comment by CHUANTU** [comment]
xcode 9， iOS11 运行的时候是有问题，自定义导航栏没有效果了

**Comment by TurkeyTeo** [comment]
ios 11 进来的时候NavigationBar设置透明度失效了
