### ISSUE TITLE
IQKeyboardManager问题

### ISSUE THREAD

**Issue by SunsgneDZ** [wangrui460/WRNavigationBar#111]
键盘收下时，页面会向上偏移。

![Uploading WechatIMG258.jpeg…]()

**Comment by SunsgneDZ** [comment]
![wechatimg258](https://user-images.githubusercontent.com/24729554/35787537-df23bb7a-0a69-11e8-8eec-181f095d20b3.jpeg)
![wechatimg259](https://user-images.githubusercontent.com/24729554/35787538-df5fd3ee-0a69-11e8-9142-5373733642cb.jpeg)

**Comment by wangrui460** [comment]
https://github.com/hackiftekhar/IQKeyboardManager/issues/1166

导航栏偏移其实是 IQKeyboard 自身的bug，它改变了 _UIBarBackground 的frame，在 AppDelegate 文件里面加上 👇的代码可以解决这个bug
IQKeyboardManager.shared().canAdjustAdditionalSafeAreaInsets = true

**Comment by SunsgneDZ** [comment]
你好，不是导航栏偏移，是底部偏移了，如上图所示。（我也试了canAdjustAdditionalSafeAreaInsets这个属性，键盘收下后，底部就出现一片白）
