### ISSUE TITLE
请问 状态栏统一设置不起作用可能是什么问题？

### ISSUE THREAD

**Issue by SunsgneDZ** [wangrui460/WRNavigationBar#113]
// 统一设置状态栏样式
 [WRNavigationBar wr_setDefaultStatusBarStyle:UIStatusBarStyleLightContent];
统一设置后，页面还是 默认的黑色。
baseNav里也未对状态栏进行设置。

**Comment by wangrui460** [comment]
https://www.jianshu.com/p/75adf70d116e
这篇文章你可能对你有帮助

**Comment by SunsgneDZ** [comment]
谢谢，是plist文件里View controller-based status bar appearance 设置为了NO造成的。
