### ISSUE TITLE
pod导入库后，源代码修改NavigationBar样式失效

### ISSUE THREAD

**Issue by runryan** [wangrui460/WRNavigationBar#121]
我之前的工程使用的官方API的方式修改NavigationBar的样式，pod导入WRNavigationBar之后，之前设置的全部都失效了，从pod移除WRNavigationBar之后，之前的设置就又生效了。也就是导入后要使用自定义的方式修改其样式吗？

**Comment by YaoJuan** [comment]
好像是这样，目前我在做项目的前期铺垫也发现的这个问题。侵入型太大了。
