### ISSUE TITLE
自定义导航栏的话，怎么给导航栏中间放一个按钮？有没有人帮帮小妹

### ISSUE THREAD

**Issue by MasterBetter** [wangrui460/WRNavigationBar#124]
我想自定义导航栏 ，我现在遇到了 想在导航栏中间放一个按钮 或者视图 和系统的一样，但是我看了代码，好像只能放一个字符串。有没有人帮帮我

**Comment by Kittycats** [comment]
你可以让 self.navgationItem.titleView = 按钮;

**Comment by NOMBER2011** [comment]
我已经弄好了，我把这个库的源码修改了下，现在自定义的导航栏和系统的差不多了，中间既可以是文字也可以是view，右边也可以放2个按钮，也可以放一个按钮，需要的话可以联系我
