### ISSUE TITLE
iOS9.0之前的系统,在切换导航栏控制器之后,收到键盘通知会崩溃.

### ISSUE THREAD

**Issue by windlesszz** [wangrui460/WRNavigationBar#126]
iOS9.0之前需要手动移除键盘通知.

**Comment by shiwensong** [comment]
@windlesszz 怎么手动移除键盘通知？修改源码？

**Comment by windlesszz** [comment]
@shiwensong 
导航栏控制器销毁的时候移除就行了

**Comment by shiwensong** [comment]
我现在是模态弹出一个imagePickerViewController,然后回到页面，点击输入框就崩溃了，按照你的意思是我在回到这个界面的时候就移除？我这样移除有错误？[[NSNotificationCenter defaultCenter] removeObserver:self.navigationController.navigationBar name:UIKeyboardDidShowNotification object:nil];
		[[NSNotificationCenter defaultCenter] removeObserver:self.navigationController.navigationBar name:UIKeyboardWillHideNotification object:nil];

**Comment by windlesszz** [comment]
@shiwensong 
你需要移除的是imagepick的那个导航栏的

**Comment by shiwensong** [comment]
可以了，感谢@windlesszz，顺便问下，只有iOS 9.0之前会出现这样的问题？iOS 9.0之后不会出现？

**Comment by windlesszz** [comment]
@shiwensong https://useyourloaf.com/blog/unregistering-nsnotificationcenter-observers-in-ios-9/

**Comment by shiwensong** [comment]
我明白了，感谢你的耐心回答。@windlesszz
