### ISSUE TITLE
-[UINavigationBar wr_keyboardDidShow]: message sent to deallocated instance 0x124e008d0

### ISSUE THREAD

**Issue by shiwensong** [wangrui460/WRNavigationBar#129]
-[UINavigationBar wr_keyboardDidShow]: message sent to deallocated instance 0x124e008d0我只是莫谈弹出了一个选择图片的视图，然后点击UITextfile,输入文字，就崩溃了。

**Comment by alexyubin** [comment]
我也是出现这个情况,

**Comment by HelloiWorld** [comment]
目前我的做法是  注释这两个通知：

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(wr_keyboardDidShow) name:UIKeyboardDidShowNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(wr_keyboardWillHide) name:UIKeyboardWillHideNotification object:nil];
