### ISSUE TITLE
能隐藏导航条的一条线吗

### ISSUE THREAD

**Issue by ws1227** [wangrui460/WRNavigationBar#13]

**Comment by wangrui460** [comment]
可以~
今天凌晨新加的功能
// 统一设置导航栏底部的分割线是否隐藏
+ (void)wr_setDefaultNavBarShadowImageHidden:(BOOL)hidden;
// 单独设置某一个控制对应的导航栏底部分割线是否隐藏
- (void)wr_setNavBarShadowImageHidden:(BOOL)hidden;

**Comment by ws1227** [comment]
隐藏线后 或者是 改变线条颜色 会引起坐标 自动上移64 有好的方案吗

**Comment by wangrui460** [comment]
我这边不存在这个问题，请问你是什么版本的
