### ISSUE TITLE
pop

### ISSUE THREAD

**Issue by MQTwist** [wangrui460/WRNavigationBar#134]

**Comment by MQGreen** [comment]
第一个push到新浪个人中心后，这个时候导航栏是透明的，直接点击返回导航栏会闪一下白色 。如果是上滑一下导航栏变成白色后再点击返回就没事了。我看了代码，是因为在透明的时候，点击返回，是获取当前界面导航栏颜色（白色）和pop后界面的导航栏颜色（蓝色）然后根据progress去过度颜色。个人觉得，在这么做的时候，先判断下导航栏的透明度，然后再过度颜色
