### ISSUE TITLE
popToRootViewControllerAnimated 导航栏会闪

### ISSUE THREAD

**Issue by wzydsw** [wangrui460/WRNavigationBar#146]
popToRootViewControllerAnimated 设置为YES的时候，导航栏会闪一下

**Comment by gongsunqingyang** [comment]
我遇到了和你一样的问题，发现调用popToRootViewController:Animated:时，wr_popToViewController:animated:调用了两次，渲染了两次导航栏，解决方法就是注释掉这几行代码：
`- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
    __weak typeof (self) weakSelf = self;
    id<UIViewControllerTransitionCoordinator> coor = [self.topViewController transitionCoordinator];
    if ([coor initiallyInteractive] == YES) {
        NSString *sysVersion = [[UIDevice currentDevice] systemVersion];
        if ([sysVersion floatValue] >= 10) {
            [coor notifyWhenInteractionChangesUsingBlock:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
                __strong typeof (self) pThis = weakSelf;
                [pThis dealInteractionChanges:context];
            }];
        } else {
            [coor notifyWhenInteractionEndsUsingBlock:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
                __strong typeof (self) pThis = weakSelf;
                [pThis dealInteractionChanges:context];
            }];
        }
        return YES;
    }
    
//    NSUInteger itemCount = self.navigationBar.items.count;
//    NSUInteger n = self.viewControllers.count >= itemCount ? 2 : 1;
//    UIViewController *popToVC = self.viewControllers[self.viewControllers.count - n];
//    [self popToViewController:popToVC animated:YES];
    return YES;
}
`

**Comment by gongsunqingyang** [comment]
我遇到了和你一样的问题，发现调用popToRootViewController:Animated:时，wr_popToViewController:animated:调用了两次，渲染了两次导航栏，解决方法就是注释掉这几行代码：
`- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
    __weak typeof (self) weakSelf = self;
    id<UIViewControllerTransitionCoordinator> coor = [self.topViewController transitionCoordinator];
    if ([coor initiallyInteractive] == YES) {
        NSString *sysVersion = [[UIDevice currentDevice] systemVersion];
        if ([sysVersion floatValue] >= 10) {
            [coor notifyWhenInteractionChangesUsingBlock:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
                __strong typeof (self) pThis = weakSelf;
                [pThis dealInteractionChanges:context];
            }];
        } else {
            [coor notifyWhenInteractionEndsUsingBlock:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
                __strong typeof (self) pThis = weakSelf;
                [pThis dealInteractionChanges:context];
            }];
        }
        return YES;
    }
    
//    NSUInteger itemCount = self.navigationBar.items.count;
//    NSUInteger n = self.viewControllers.count >= itemCount ? 2 : 1;
//    UIViewController *popToVC = self.viewControllers[self.viewControllers.count - n];
//    [self popToViewController:popToVC animated:YES];
    return YES;
}
`
