### ISSUE TITLE
系统相册页面问题

### ISSUE THREAD

**Issue by JarvisHot** [wangrui460/WRNavigationBar#15]
跳转选择相册UIImagePickerController 页面，`[picker navigationBar].titleTextAttributes = @{NSForegroundColorAttributeName: [UIColor whiteColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:17]};
        [picker.navigationBar setTintColor:[UIColor blackColor]];`
更改相册导航栏颜色代码无效

**Comment by wangrui460** [comment]
[self wr_setNavBarBarTintColor:[UIColor whiteColor]];
请用我提供的这个方法来更改导航栏颜色

**Comment by JarvisHot** [comment]
我用的是自定义的navbar  ` [self wr_setCustomNavBar:self.navBar];`
导航是白色，`[self wr_setNavBarBarTintColor:[UIColor whiteColor]];`这个代码只能改相册之前的页面的导航颜色，present过来的imagepicker的颜色还是改不了，是不是runtime 更改了imagepicker的导航颜色？
