### ISSUE TITLE
iPhoneXs Max和 iPhoneXR获取导航栏底部高度不对

### ISSUE THREAD

**Issue by TonyGJJ** [wangrui460/WRNavigationBar#150]
+ (BOOL)isIphoneX {
    struct utsname systemInfo;
    uname(&systemInfo);
    NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
    if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
        // judgment by height when in simulators
        return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)));
    }
    BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
    return isIPhoneX;
}

得到的结果为NO

**Comment by Salah-ad-Din** [comment]
> * (BOOL)isIphoneX {
>   struct utsname systemInfo;
>   uname(&systemInfo);
>   NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
>   if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
>   // judgment by height when in simulators
>   return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
>   CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)));
>   }
>   BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
>   return isIPhoneX;
>   }
> 
> 得到的结果为NO

目前貌似不更新了，临时hook处理一下吧：）

@implementation WRNavigationBar (isIPhoneX)

+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self swizzWithClass:[self class] originSel:NSSelectorFromString(@"isIphoneX") newSel:@selector(swizz_isIphoneX)];
    });
}

+ (BOOL)swizz_isIphoneX
{
    //your method
}

+ (void)swizzWithClass:(Class)class originSel:(SEL)originSel newSel:(SEL)newSel
{
    Method origMethod = class_getClassMethod(class, originSel);
    Method altMethod = class_getClassMethod(class, newSel);
    if (!origMethod || !altMethod) {
        return;
    }
    Class metaClass = object_getClass(class);
    BOOL didAddMethod = class_addMethod(metaClass,originSel,
                                        method_getImplementation(altMethod),
                                        method_getTypeEncoding(altMethod));
    
    if (didAddMethod) {
        class_replaceMethod(metaClass,newSel,
                            method_getImplementation(origMethod),
                            method_getTypeEncoding(origMethod));
    } else {
        method_exchangeImplementations(origMethod, altMethod);
    }
}

@end

**Comment by Salah-ad-Din** [comment]
> * (BOOL)isIphoneX {
>   struct utsname systemInfo;
>   uname(&systemInfo);
>   NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
>   if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
>   // judgment by height when in simulators
>   return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
>   CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)));
>   }
>   BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
>   return isIPhoneX;
>   }
> 
> 得到的结果为NO

目前貌似不更新了，临时hook处理一下吧：）

```
@implementation WRNavigationBar (isIPhoneX)

+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self swizzWithClass:[self class] originSel:NSSelectorFromString(@"isIphoneX") newSel:@selector(swizz_isIphoneX)];
    });
}

+ (BOOL)swizz_isIphoneX
{
    return [[UIDevice currentDevice] wbt_isIPhoneX_or_isIPhoneXMax];
}

+ (void)swizzWithClass:(Class)class originSel:(SEL)originSel newSel:(SEL)newSel
{
    Method origMethod = class_getClassMethod(class, originSel);
    Method altMethod = class_getClassMethod(class, newSel);
    if (!origMethod || !altMethod) {
        return;
    }
    Class metaClass = object_getClass(class);
    BOOL didAddMethod = class_addMethod(metaClass,originSel,
                                        method_getImplementation(altMethod),
                                        method_getTypeEncoding(altMethod));
    
    if (didAddMethod) {
        class_replaceMethod(metaClass,newSel,
                            method_getImplementation(origMethod),
                            method_getTypeEncoding(origMethod));
    } else {
        method_exchangeImplementations(origMethod, altMethod);
    }
}

@end
```

**Comment by Salah-ad-Din** [comment]
> * (BOOL)isIphoneX {
>   struct utsname systemInfo;
>   uname(&systemInfo);
>   NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
>   if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
>   // judgment by height when in simulators
>   return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
>   CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)));
>   }
>   BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
>   return isIPhoneX;
>   }
> 
> 得到的结果为NO

目前貌似不更新了，临时hook处理一下吧：）
```
@implementation WRNavigationBar (isIPhoneX)

+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self swizzWithClass:[self class] originSel:NSSelectorFromString(@"isIphoneX") newSel:@selector(swizz_isIphoneX)];
    });
}

+ (BOOL)swizz_isIphoneX
{
    //your method
}

+ (void)swizzWithClass:(Class)class originSel:(SEL)originSel newSel:(SEL)newSel
{
    Method origMethod = class_getClassMethod(class, originSel);
    Method altMethod = class_getClassMethod(class, newSel);
    if (!origMethod || !altMethod) {
        return;
    }
    Class metaClass = object_getClass(class);
    BOOL didAddMethod = class_addMethod(metaClass,originSel,
                                        method_getImplementation(altMethod),
                                        method_getTypeEncoding(altMethod));
    
    if (didAddMethod) {
        class_replaceMethod(metaClass,newSel,
                            method_getImplementation(origMethod),
                            method_getTypeEncoding(origMethod));
    } else {
        method_exchangeImplementations(origMethod, altMethod);
    }
}

@end
```

**Comment by LwqDeveloper** [comment]
改下 [WRNavigationBar isIphoneX]判断就好了，比如

(BOOL)isIphoneX {
struct utsname systemInfo;
uname(&systemInfo);
NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
// judgment by height when in simulators
return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)) ||
CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(414, 896)) ||
CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(896, 414)));
}
BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
return isIPhoneX;
}

**Comment by Toga21** [comment]
> 改下 [WRNavigationBar isIphoneX]判断就好了，比如
> 
> (BOOL)isIphoneX {
> struct utsname systemInfo;
> uname(&systemInfo);
> NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
> if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
> // judgment by height when in simulators
> return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
> CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)) ||
> CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(414, 896)) ||
> CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(896, 414)));
> }
> BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"] || [platform isEqualToString:@"iPhone11,2"]|| [platform isEqualToString:@"iPhone11,4"]|| [platform isEqualToString:@"iPhone11,6"]|| [platform isEqualToString:@"iPhone11,8"];
> return isIPhoneX;
> }
