### ISSUE TITLE
跳转到  TZImagePickerController 框架的时候导航栏变成了白色。

### ISSUE THREAD

**Issue by Victory886** [wangrui460/WRNavigationBar#151]
跳转到  TZImagePickerController 框架的时候导航栏变成了白色。
过滤也不行，没有效果。

**Comment by caofutao** [comment]
我也遇到这样的问题了

**Comment by Liyongcong** [comment]
我也遇到，有解决方案么

**Comment by huicongfu** [comment]
对，我也一样，用黑白名单也不行···各位现在解决了吗？

**Comment by henusjj** [comment]
我也是这个问题，TZImagePickerController 框架的时候导航栏变成了白色，自定义的nav，设置都无效，怎么办，请问有解决的办法吗？
