### ISSUE TITLE
iOS12 present 出来的页面 设置导航条背景色失败

### ISSUE THREAD

**Issue by llt3677** [wangrui460/WRNavigationBar#153]
present 出来的 navigation controller 设置背景色不起作用

**Comment by Starryxu** [comment]
![snip20181123_15](https://user-images.githubusercontent.com/19592642/48942875-231e0600-ef5c-11e8-9356-4d2b46bc2a41.png)
这里为空了，backgroundView没有添加上去

**Comment by llt3677** [comment]
> 请问你怎么解决的

我重写的WRNavigationBar的 insertSubview 方法，判断如果没加上再重新加一次
![1071544506079_ pic_hd](https://user-images.githubusercontent.com/20432715/49780278-d488ae00-fd48-11e8-977e-d38b13872a11.jpg)
open override func insertSubview(_ view: UIView, at index: Int) {
        
        super.insertSubview(view, at: index)
        
        if view.isKind(of: NSClassFromString("_UIBarBackground")!) {
            
            if let bg = self.backgroundView,!view.subviews.contains(bg) {
                
                view.insertSubview(bg, at: 0)
                
                backgroundView?.snp.makeConstraints({ maker in
                    
                    maker.edges.equalToSuperview()
                })
            }
        }
    }

**Comment by Liyongcong** [comment]
有oc的么

**Comment by llt3677** [comment]
> 有oc的么

- (void)insertSubview:(UIView *)view atIndex:(NSInteger)index {
    
    [super insertSubview:view atIndex:index];
    
    if ([view isKindOfClass:NSClassFromString(@"_UIBarBackground")]) {
        
        if (![view.subviews containsObject:self.backgroundView]) {

            [view insertSubview:self.backgroundView atIndex:0];
        
            [self.backgroundView mas_makeConstraints:^(MASConstraintMaker *make) {
                
                make.edges.equalTo(view.superview);
            }];
        }
    }
}

**Comment by zhoumingwu** [comment]
Thanks
