### ISSUE TITLE
模拟器上XS,XS_Max,XR，导航栏会有问题（真机我没有测，您可以试试）

### ISSUE THREAD

**Issue by 841766048** [wangrui460/WRNavigationBar#155]
我是在你写的WRNavigationBar.m文件里修改了一下
我先添加了一些宏
//判断是否是ipad
#define isPad ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad)
//判断iPhoneX
#define IS_IPHONE_X ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1125, 2436), [[UIScreen mainScreen] currentMode].size) && !isPad : NO)
//判断iPHoneXr
#define IS_IPHONE_Xr ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(828, 1792), [[UIScreen mainScreen] currentMode].size) && !isPad : NO)
//判断iPhoneXs
#define IS_IPHONE_Xs ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1125, 2436), [[UIScreen mainScreen] currentMode].size) && !isPad : NO)
//判断iPhoneXs Max
#define IS_IPHONE_Xs_Max ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1242, 2688), [[UIScreen mainScreen] currentMode].size) && !isPad : NO)

然后再+ (BOOL)isIphoneX方法里进行修改
+ (BOOL)isIphoneX {
    struct utsname systemInfo;
    uname(&systemInfo);
    NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
    if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
        // judgment by height when in simulators
//        return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
//                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)));
        if(IS_IPHONE_X==YES){
            return YES;
        }else if (IS_IPHONE_Xr ==YES){
            return YES;
        }else if (IS_IPHONE_Xs ==YES){
            return YES;
        }else if (IS_IPHONE_Xs_Max ==YES){
            return YES;
        }else{
            return NO;
        }
    }
//    BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
//    NSLog(@"isIPhoneX = %d",isIPhoneX);
//    return isIPhoneX;
    if(IS_IPHONE_X==YES){
        return YES;
    }else if (IS_IPHONE_Xr ==YES){
        return YES;
    }else if (IS_IPHONE_Xs ==YES){
        return YES;
    }else if (IS_IPHONE_Xs_Max ==YES){
        return YES;
    }else{
        return NO;
    }

}
这样就好了

**Comment by liang37038** [comment]
正好发现问题了，参考一下

**Comment by czl0325** [comment]
我也发现了，作者都不改改bug

**Comment by inoryshu** [comment]
你这个是跟作者一样的懒，固定判断某种机型，这是不对的想法，你应该直接获取当前的状态栏高度加上导航栏的高度就行了。

**Comment by a714857512** [comment]
> 你这个是跟作者一样的懒，固定判断某种机型，这是不对的想法，你应该直接获取当前的状态栏高度加上导航栏的高度就行了。

额，我这边当前导航栏和状态栏可能会有一开始隐藏的可能。这样的话，不知道判断的是否会准确

**Comment by inoryshu** [comment]
> > 你这个是跟作者一样的懒，固定判断某种机型，这是不对的想法，你应该直接获取当前的状态栏高度加上导航栏的高度就行了。
> 
> 额，我这边当前导航栏和状态栏可能会有一开始隐藏的可能。这样的话，不知道判断的是否会准确

我已经放弃了，在iOS12版本太多问题了，关键问题present导航栏属性设置无效问题，一直改不好！能力有限，暂时放弃这个库了

**Comment by 814349837** [comment]
https://github.com/wangrui460/WRNavigationBar/pull/167

**Comment by xulifeiyu900201** [comment]
+ (BOOL)isIphoneX {
    struct utsname systemInfo;
    uname(&systemInfo);
    NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
    if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
        // judgment by height when in simulators
        return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(414, 896)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(896, 414)));
    }
    BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] ||
                     [platform isEqualToString:@"iPhone10,6"] ||
                     [platform isEqualToString:@"iPhone11,2"] ||
                     [platform isEqualToString:@"iPhone11,4"] ||
                     [platform isEqualToString:@"iPhone11,6"] ||
                     [platform isEqualToString:@"iPhone11,8"];
    return isIPhoneX;
}

**Comment by Kienty** [comment]
你的宏定义好多⚠️，我用了我自己项目中的，然后写了一个判断，感觉比较简洁，不知道有问题没有。

//判断iPHoneX

\#define IS_IPHONE_X ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1125, 2436), [[UIScreen mainScreen] currentMode].size) : NO)

//判断iPHoneXr

\#define IS_IPHONE_Xr ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(828, 1792), [[UIScreen mainScreen] currentMode].size) : NO)

//判断iPhoneXs

\#define IS_IPHONE_Xs ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1125, 2436), [[UIScreen mainScreen] currentMode].size) : NO)

//判断iPhoneXs Max

\#define IS_IPHONE_Xs_Max ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1242, 2688), [[UIScreen mainScreen] currentMode].size): NO)

```objective-c

+ (BOOL)isIphoneX {
    return ((IS_IPHONE_X==YES || IS_IPHONE_Xr ==YES || IS_IPHONE_Xs== YES || IS_IPHONE_Xs_Max== YES) ? YES : NO);
}
```
