### ISSUE TITLE
ios12 presentViewController出来的会先透明然后闪一下

### ISSUE THREAD

**Issue by jueduibishi** [wangrui460/WRNavigationBar#159]
用xcode10编译，rt。。。

**Comment by SummerHH** [comment]
我也发现这个问题了,模态出来的时候有时候导航会闪一下才变回了,你怎么解决的

**Comment by inoryshu** [comment]
我是透明了就出不来了，一直是透明的

**Comment by Liyongcong** [comment]
我的也是，你们怎么解决的

**Comment by hooviel** [comment]
同问

**Comment by hooviel** [comment]
答案在 #168

**Comment by Liyongcong** [comment]
好的，我试试，谢谢
原始邮件
发件人:Davidnotifications@github.com
收件人:wangrui460/WRNavigationBarWRNavigationBar@noreply.github.com
抄送:Liyongcong570703516@qq.com; Commentcomment@noreply.github.com
发送时间:2019年3月15日(周五) 19:21
主题:Re: [wangrui460/WRNavigationBar] ios12 presentViewController出来的会先透明然后闪一下 (#159)


答案在 #168
