### ISSUE TITLE
两个都是隐藏了导航栏的VC，侧滑返回的时候蓝色会出现。

### ISSUE THREAD

**Issue by huanglins** [wangrui460/WRNavigationBar#16]
如题。

**Comment by wangrui460** [comment]
你更新一下最新代码吧，我新增了一个连续多个界面导航栏透明的demo，没有出现蓝色，你看看

**Comment by huanglins** [comment]
谢谢🤡🤡




发自网易邮箱大师
在2017年07月22日 12:10，wangrui460 写道：

Closed #16.
