### ISSUE TITLE
在真机上跑可能存在swizzling部分系统方法失效例如pushViewController

### ISSUE THREAD

**Issue by hoyawolfer** [wangrui460/WRNavigationBar#161]
解决办法, 将作者的swizzing方法优化
![screen shot 2018-11-16 at 2 23 06 pm](https://user-images.githubusercontent.com/12148547/48601570-43255680-e9ab-11e8-8b48-c618f6915020.png)

**Comment by bigNiuSanMao** [comment]
楼主，这个问题 怎么能够复现呢，我们用户有报这个问题，但找不到 复现的方法
