### ISSUE TITLE
ios12 presentViewController出来的会先透明然后闪一下,有时候直接是纯白色，不知道怎么解决

### ISSUE THREAD

**Issue by Liyongcong** [wangrui460/WRNavigationBar#168]

**Comment by hooviel** [comment]
同问

**Comment by hooviel** [comment]
UINavigationBar (WRAddition) 中添加如下代码，同时修复横屏背景高度问题；

- (void)insertSubview:(UIView *)view atIndex:(NSInteger)index {
    [super insertSubview:view atIndex:index];
    if ([view isKindOfClass:NSClassFromString(@"_UIBarBackground")]) {
        view.clipsToBounds = YES;
        if (![view.subviews containsObject:self.backgroundView]) {
            [view insertSubview:self.backgroundView atIndex:0];
        }
    }
}
