### ISSUE TITLE
在横屏状态下，切换回竖屏，导航栏上变白，子元素不见了？

### ISSUE THREAD

**Issue by mengxinyizhui** [wangrui460/WRNavigationBar#170]
![untitled](https://user-images.githubusercontent.com/14011250/50223952-85d9b480-03d7-11e9-8237-37cbd7c40065.gif)

**Comment by mengxinyizhui** [comment]
我开始首页Page1    不见了

**Comment by mengxinyizhui** [comment]
我开始首页的 标题    `page1` 不见了

**Comment by libercata** [comment]
(BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
试试把这个方法注了
