### ISSUE TITLE
Xcode10 iOS12中用XsMAX和XR运行 导航栏有一块是透明的 其他机型没问题

### ISSUE THREAD

**Issue by b1003572686** [wangrui460/WRNavigationBar#171]
![ac42a912-84c6-4af3-9475-4d8ae2714e8b](https://user-images.githubusercontent.com/17485637/50335931-d112d500-0547-11e9-8af6-e52d93a5fc89.png)
![5b33e5c0-dfe3-47b2-ad4e-44bf9b50a078](https://user-images.githubusercontent.com/17485637/50335936-d4a65c00-0547-11e9-8a61-54001835a9f8.png)

**Comment by MMschool** [comment]
他没有适配,你找到他里面判断iPhone X的地方改改就可以

**Comment by b1003572686** [comment]
> 他没有适配,你找到他里面判断iPhone X的地方改改就可以

OK

**Comment by xulifeiyu900201** [comment]
+ (BOOL)isIphoneX {
    struct utsname systemInfo;
    uname(&systemInfo);
    NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
    if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
        // judgment by height when in simulators
        return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(414, 896)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(896, 414)));
    }
    BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] ||
                     [platform isEqualToString:@"iPhone10,6"] ||
                     [platform isEqualToString:@"iPhone11,2"] ||
                     [platform isEqualToString:@"iPhone11,4"] ||
                     [platform isEqualToString:@"iPhone11,6"] ||
                     [platform isEqualToString:@"iPhone11,8"];
    return isIPhoneX;
}

**Comment by chenjianlei** [comment]
+ (CGFloat)navBarBottom {
    return [UIApplication sharedApplication].statusBarFrame.size.height + 44;
}

+ (CGFloat)tabBarHeight {
    if (@available(iOS 11.0, *)) {
        return [UIApplication sharedApplication].delegate.window.safeAreaInsets.bottom + 49;
    } else {
        return 49;
    }
}

这样就可以了

**Comment by xuhuaping** [comment]
> 他没有适配，你找到他里面判断iPhone X的地方改改就可以

改了没反应

**Comment by hooviel** [comment]
WRNavigationBar.m 中修改

`+ (BOOL)isIphoneX {
    static BOOL isX;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        CGSize size = UIScreen.mainScreen.bounds.size;
        CGFloat width = MIN(size.width, size.height);
        size.height = MAX(size.width, size.height);
        size.width = width;
        if (CGSizeEqualToSize(size, CGSizeMake(375, 812))||
            CGSizeEqualToSize(size, CGSizeMake(414, 896))) {
            isX = YES;
        }
        else {
            isX = NO;
        }
    });
    return isX;
}`

**Comment by RtzX** [comment]
以上方案 只能是普通的有效 <即demo里的 第一个Tabbar<`常用`>>. 
在第二个 Demo `自定义导航栏` 还是有问题的  
还需要修改 `WRCustomNavigationBar` 这个

**Comment by chenjianlei** [comment]
> 以上方案 只能是普通的有效 <即demo里的 第一个Tabbar<`常用`>>.
> 在第二个 Demo `自定义导航栏` 还是有问题的
> 还需要修改 `WRCustomNavigationBar` 这个

-(void)updateFrame {
//    NSInteger top = ([WRCustomNavigationBar isIphoneX]) ? 44 : 20;
    NSInteger top = [UIApplication sharedApplication].statusBarFrame.size.height;
    NSInteger margin = 0;
    NSInteger buttonHeight = 44;
    NSInteger buttonWidth = 44;
    NSInteger titleLabelHeight = 44;
    NSInteger titleLabelWidth = 180;

    self.backgroundView.frame = self.bounds;
    self.backgroundImageView.frame = self.bounds;
    self.leftButton.frame = CGRectMake(margin, top, buttonWidth, buttonHeight);
    self.rightButton.frame = CGRectMake(kWRScreenWidth - buttonWidth - margin, top, buttonWidth, buttonHeight);
    self.titleLable.frame = CGRectMake((kWRScreenWidth - titleLabelWidth) / 2, top, titleLabelWidth, titleLabelHeight);
    self.bottomLine.frame = CGRectMake(0, (CGFloat)(self.bounds.size.height-0.5), kWRScreenWidth, 0.5);
}

我当时是这么改的

**Comment by RtzX** [comment]
> > 以上方案 只能是普通的有效 <即demo里的 第一个Tabbar<`常用`>>.
> > 在第二个 Demo `自定义导航栏` 还是有问题的
> > 还需要修改 `WRCustomNavigationBar` 这个
> 
> -(void)updateFrame {
> // NSInteger top = ([WRCustomNavigationBar isIphoneX]) ? 44 : 20;
> NSInteger top = [UIApplication sharedApplication].statusBarFrame.size.height;
> NSInteger margin = 0;
> NSInteger buttonHeight = 44;
> NSInteger buttonWidth = 44;
> NSInteger titleLabelHeight = 44;
> NSInteger titleLabelWidth = 180;
> 
> ```
> self.backgroundView.frame = self.bounds;
> self.backgroundImageView.frame = self.bounds;
> self.leftButton.frame = CGRectMake(margin, top, buttonWidth, buttonHeight);
> self.rightButton.frame = CGRectMake(kWRScreenWidth - buttonWidth - margin, top, buttonWidth, buttonHeight);
> self.titleLable.frame = CGRectMake((kWRScreenWidth - titleLabelWidth) / 2, top, titleLabelWidth, titleLabelHeight);
> self.bottomLine.frame = CGRectMake(0, (CGFloat)(self.bounds.size.height-0.5), kWRScreenWidth, 0.5);
> ```
> }
> 
> 我当时是这么改的

  > 不需要这么麻烦. 其实只需要修改一下 判断 `全面屏` 的方法就好了
    
       #define IPHONE_X \
     ({BOOL isPhoneX = NO;\
    if (@available(iOS 11.0, *)) {\
    isPhoneX = [[UIApplication sharedApplication] delegate].window.safeAreaInsets.bottom > 0.0;\
    }\
    (isPhoneX);})

作者在 `WRNavigationBar.h` 和 `WRCustomNavigationBar` 写了两个判断 `iPhone X` 机型的方法 
在作者的  `isIphoneX` 方法中 直接返回 上面定义的 宏就好了..  世界恢复了 安静

**Comment by RtzX** [comment]
现在是 不管是在 `全面屏`  还是 `普通屏` 在  `IQKeyboardManager` 下都有问题... 什么情况啊

**Comment by mrZombie2016** [comment]
我直接这样改的
```
+ (BOOL)isIphoneX {
    return CGRectGetHeight([[UIApplication sharedApplication] statusBarFrame]) > 20;
}
```

**Comment by RtzX** [comment]
反正我是放弃使用这个库了.... 太久不更新了... 也没人维护了..

**Comment by mrZombie2016** [comment]
> 反正我是放弃使用这个库了.... 太久不更新了... 也没人维护了..

还可以，挺好用的，自己稍微改改就好了

**Comment by ruixingchen** [comment]
由于作者已经不维护了, 我fork了一份后, 添加了 iOS12 支持, 添加了MAX, 全面屏 iPad Pro 支持
这里 --> https://github.com/ruixingchen/WRNavigationBar
