### ISSUE TITLE
出现Bug的同学可以看看我的fork

### ISSUE THREAD

**Issue by ruixingchen** [wangrui460/WRNavigationBar#174]
由于作者已经不维护了, 我fork了一份后, 添加了 iOS12 支持, 添加了MAX, 全面屏 iPad Pro 支持
这里 --> https://github.com/ruixingchen/WRNavigationBar

**Comment by ruixingchen** [comment]
我的 fork 最低支持 iOS 11, 按需选择或者有更低要求的自己拿去改一改吧

**Comment by zhanglichuan** [comment]
> 由于作者已经不维护了, 我fork了一份后, 添加了 iOS12 支持, 添加了MAX, 全面屏 iPad Pro 支持
> 这里 --> https://github.com/ruixingchen/WRNavigationBar

https://github.com/wangrui460/WRNavigationBar/issues/174#issue-434072086

**Comment by zhanglichuan** [comment]
@ruixingchen  你的工程运行不了，报错

**Comment by zhanglichuan** [comment]
@ruixingchen 你的工程运行不了，报错
dyld: Library not loaded: @rpath/RevealServer.framework/RevealServer
  Referenced from: /var/containers/Bundle/Application/8FE118CC-B035-4591-9218-65B8D5FEDC82/CodeDemo.app/CodeDemo
  Reason: image not found
Message from debugger: Terminated due to signal 6

**Comment by zhanglichuan** [comment]
@ruixingchen 应该是你的Reveal-SDK，这个是干啥的？我直接去掉了

**Comment by zhanglichuan** [comment]
@ruixingchen  你那边不能直接用pod么，弄一个啥

**Comment by zhanglichuan** [comment]
> 由于作者已经不维护了, 我fork了一份后, 添加了 iOS12 支持, 添加了MAX, 全面屏 iPad Pro 支持
> 这里 --> https://github.com/ruixingchen/WRNavigationBar

你这个再打电话，定位时候，你获取的高度是不对的

**Comment by bruceWangDev** [comment]
@ruixingchen 拉取你的代码 运行先报 pod 的错误 pod install 之后 报找不到 navBarBottom 有点无奈 ..

**Comment by ruixingchen** [comment]
@bruceWangDev  上次commit了一个修复, 可能没做好检查, 我过几天看看

**Comment by bruceWangDev** [comment]
@ruixingchen  好的~ 谢谢~

**Comment by xxf850020** [comment]
对IQKeyboardManager还是有bug。

**Comment by yxx19950523** [comment]
你好，我想问一下，你的微博demo隐藏，会把下面的tabbar对应的item也隐藏，该如何解决?

**Comment by ruixingchen** [comment]
@yxx19950523 我已经放弃使用原生导航栏改用自定义的导航栏了，原生导航栏实在不好控制

**Comment by lifeMiik** [comment]
请问各位，如果适配了暗黑模式的情况下，点击跳转到 子页面会闪一下（白色背景）是如何解决的
