### ISSUE TITLE
既然已经不维护建议标记为deprecated，个人目前不建议使用

### ISSUE THREAD

**Issue by che11o2u** [wangrui460/WRNavigationBar#179]

**Comment by listenzz** [comment]
建议使用 [HBDNavigationBar](https://github.com/listenzz/HBDNavigationBar)

**Comment by DogTwoChen** [comment]
HBDNavigationBar delegate被设置就会导致失效,也不建议使用

**Comment by Kienty** [comment]
目前有好用的吗？

**Comment by listenzz** [comment]
@DogTwoChen delegate 的问题已解决

**Comment by alexiscn** [comment]
建议使用 [WXNavigationBar](https://github.com/alexiscn/WXNavigationBar)
