### ISSUE TITLE
isIPhoneX 判断条件错误

### ISSUE THREAD

**Issue by quanh** [wangrui460/WRNavigationBar#184]
isIPhoneX 判断是错误的。会误判X系列为非X系列

**Comment by LChao05** [comment]
+ (BOOL)isIphoneX {
     return [[[UIDevice currentDevice] systemVersion] floatValue] >= 11.f && (MIN([UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height) >= 375 && MAX([UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height) >= 812);
}
我改了代码

**Comment by Andy0570** [comment]
```Objective-C
// 判断是否为异形屏
- (BOOL)isiPhoneX {
    // 先判断当前设备是否为 iPhone 或 iPad
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone) {
        // 获取屏幕的高度
        CGFloat screenHeight = kScreenHeight;
        // 异形屏尺寸：375x812、414x896
        if (screenHeight == 812.0f || screenHeight == 896.0f) {
            return YES;
        }
    }
    return NO;
}
```
