### ISSUE TITLE
测试IQKeyboard的问题

### ISSUE THREAD

**Issue by ke112** [wangrui460/WRNavigationBar#192]
如下图,当弹起键盘侧滑后,tabbar上来了,下不去了.

![Simulator Screen Shot - iPhone 12 - 2021-07-15 at 09 45 43](https://user-images.githubusercontent.com/45870862/125715000-1e7d9c31-8438-4a7a-b56e-91cf34064e05.png)
![Simulator Screen Shot - iPhone 12 - 2021-07-15 at 09 45 38](https://user-images.githubusercontent.com/45870862/125715006-c0d1b988-41d3-4715-a871-72d4fa1bef75.png)

**Comment by ke112** [comment]
大佬,以为你pod更新了,发现问题后 结果一看 只是改了ReadMe...怪不得

**Comment by wangrui460** [comment]
加我微信 wr1204607318

**Comment by wangrui460** [comment]
我重新提交了一个版本，或者你直接把iqkeyboard 版本升级到最新版，这个问题就不存在了
