### ISSUE TITLE
wr_setStatusBarStyle does not work

### ISSUE THREAD

**Issue by litt1e-p** [wangrui460/WRNavigationBar#20]
Hi @wangrui460 , the statusBarStyle does not changed after I used `wr_setStatusBarStyle`, is it needs some additional codes there?

**Comment by wangrui460** [comment]
Of course, it's affected by a lot of conditions. You can Google how to modify the status bar style

**Comment by litt1e-p** [comment]
@wangrui460 I know how to modify statusbar style. I was thinking changing the style via `wr_setStatusBarStyle` simply. But it seems impossible.

**Comment by wangrui460** [comment]
I change the style simply by wr_setStatusBarStyle in Demo, you can see it

**Comment by litt1e-p** [comment]
@wangrui460 my app is different which contains a side menu controller, maybe it can not use `WRNavigationBar`, thanks
