### ISSUE TITLE
有个小bug，麻烦您看下哈~

### ISSUE THREAD

**Issue by DreamBuddy** [wangrui460/WRNavigationBar#21]
当window的rootViewController是UITabbarController时，UITabbarController包含几个UINavigationController 这时候 第一个 UINavigationController中的VC设置 [self wr_setNavBarBackgroundAlpha:0]; 但是导航栏的Alpha不是0。。

**Comment by DreamBuddy** [comment]
edgesForExtendedLayout 跟这个属性有关系~

**Comment by DreamBuddy** [comment]
BackGroundImage 和 BarBarTintColor 这里不能并存啊~

**Comment by wangrui460** [comment]
所以如果想使用BackGroundImage，建议使用自定义导航栏
