### ISSUE TITLE
UIVisualEffectVIew 影响导航栏变透明。

### ISSUE THREAD

**Issue by AlwaysYang** [wangrui460/WRNavigationBar#26]
使用wr_setNavBarBackgroundAlpha:0 使导航栏变为透明。 导航栏会出现UIVisualEffectVIew 影响了导航栏显示透明
![94ca327d-6040-4511-a9b9-8857a9a230b2](https://user-images.githubusercontent.com/14845272/28865809-b136de58-77a3-11e7-9a7c-8008c60a4b06.png)
![278f5138-092c-4f36-8dbb-8cc819c2ee96](https://user-images.githubusercontent.com/14845272/28865810-b17dfc84-77a3-11e7-949e-105e3f9f3130.png)

**Comment by wangrui460** [comment]
现在还有问题吗？

**Comment by AlwaysYang** [comment]
我不知道现在有没有问题，我当时集成进去没有搞定这个问题，就换了另一种方式实现了。所以现在没有用wr。 但还是感谢你提供的框架。
