### ISSUE TITLE
有个问题请教下

### ISSUE THREAD

**Issue by lxzjsj** [wangrui460/WRNavigationBar#29]
直接在tab接到界面上，导航栏变成白色的了，啥都不显示，跟踪了下代码，if和else都没有进去，但是通过其它界面导航进来没问题，这是为什么？
- (void)wr_setNavBarBarTintColor:(UIColor *)color
{
    objc_setAssociatedObject(self, &kWRNavBarBarTintColorKey, color, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    UIView *view = [self wr_customNavBar];
    if ([[self wr_customNavBar] isKindOfClass:[UINavigationBar class]])
    {
        UINavigationBar *navBar = (UINavigationBar *)[self wr_customNavBar];
        [navBar wr_setBackgroundColor:color];
    }
    else
    {
        if ([self pushToCurrentVCFinished] == YES && [self pushToNextVCFinished] == NO) {
            [self.navigationController setNeedsNavigationBarUpdateForBarTintColor:color];
        }
    }
}

**Comment by wangrui460** [comment]
新版本可能已经解决
