### ISSUE TITLE
有alter弹出的时候被推出的自控制器会变为透明导航栏。这个页面的上一个是透明导航栏。

### ISSUE THREAD

**Issue by lp380490944** [wangrui460/WRNavigationBar#30]
![image](https://user-images.githubusercontent.com/13585771/29153690-8260f8a6-7dc1-11e7-942d-397f727961b0.png)

**Comment by wangrui460** [comment]
好，有时间了我会解决

**Comment by JIAZoro** [comment]
解决了吗，也碰到这个问题
