### ISSUE TITLE
会影响到其它三方库内部的navigationbar的样式

### ISSUE THREAD

**Issue by lucifer001** [wangrui460/WRNavigationBar#32]
比如我用MWPhotoBrowser，navigationbar 会在 viewWillAppear时变为白色（默认颜色）。所以要不要考虑下不要用分类的方式

**Comment by HughLi** [comment]
侵入确实比较强 建议不要用分类,会影响到一些特殊页面的设置情况

**Comment by losedMemory** [comment]
确实会影响别的第三方库,这样做很不友好啊,还得去改第三方,这实在太麻烦了

**Comment by wangrui460** [comment]
1.2.0 版本中加入了 黑名单功能，可将不需要改变的控制器加入 blackList 列表里
