### ISSUE TITLE
wr_pushViewController:不执行

### ISSUE THREAD

**Issue by zfx5130** [wangrui460/WRNavigationBar#33]
你好，我tabbar 控制的导航条是用storyborad 布局的， 但是用你的实现，这句方法不执行，为什么
wr_pushViewController:(UIViewController *)viewController animated:(BOOL)animated

你的方法，是当push 设置为yes才能执行，所以一直卡在这里 不能调用次方法里面的内容

**Comment by wangrui460** [comment]
这个问题前几天好像解决了，你可以看一下
