### ISSUE TITLE
侧滑中，会随机出现竖线。

### ISSUE THREAD

**Issue by huanglins** [wangrui460/WRNavigationBar#34]
![image](https://user-images.githubusercontent.com/10528244/29600423-5597d06e-8808-11e7-87d3-637ce3cb830d.png)

![image](https://user-images.githubusercontent.com/10528244/29600553-2db032fc-8809-11e7-8943-9b3825e63033.png)

![image](https://user-images.githubusercontent.com/10528244/29600557-32a37c10-8809-11e7-8c15-534529fe20d5.png)

出现的设备：iPhone6 | iOS 9.3.5

**Comment by wangrui460** [comment]
这种问题应该跟导航栏没有什么关系
