### ISSUE TITLE
runtime的代码影响范围太大，建议用类别或其他方式来写

### ISSUE THREAD

**Issue by heyehao2008** [wangrui460/WRNavigationBar#39]
runtime的代码作用于全局，会影响系统默认导航栏的毛玻璃效果或其他第三方库中导航栏的效果。项目中使用默认导航栏毛玻璃样式，加入该库的头文件后，毛玻璃效果就没有了，虽然设置导航栏颜色，透明度等挺方便

**Comment by SummerHF** [comment]
可以将UIViewController这个分类修改为自定义的viewController的分类 
@interface UIViewController (WRAddition)
change 为
@interface 你自定义的控制器 (WRAddition)
如何

**Comment by Doraemonyy** [comment]
类别该如何去实现呢？

**Comment by wangrui460** [comment]
1.2.0 版本中加入了 黑名单功能，可将不需要改变的控制器加入 blackList 列表里
