### ISSUE TITLE
iOS11会失效

### ISSUE THREAD

**Issue by clarenceli** [wangrui460/WRNavigationBar#4]
猜是在iOS11下 _UIBarBackround的alpha最后又被系统设成了1，时机问题。

**Comment by wangrui460** [comment]
刚装了iOS11，并没有出现失效的问题

**Comment by clarenceli** [comment]
我的是Xcode9 模拟器的iOS11，确实透明有问题，别的issue也提到这个问题了。

**Comment by clarenceli** [comment]
![simulator screen shot 19 jun 2017 11 05 24](https://user-images.githubusercontent.com/6646766/27267996-38d56556-54df-11e7-874b-c4a44567d1d3.png)

**Comment by wangrui460** [comment]
哈哈，我没想到你是用模拟器测得，我直接给手机升级了iOS11，在常用中是正常的，所以不排除是模拟器的bug，不过我会关注这个问题的。


![640ed7a1603b5757ff91ff1dd4be7a68](https://user-images.githubusercontent.com/11909313/27269041-26f877b8-54e6-11e7-9476-5bac8a38df3a.png)
