### ISSUE TITLE
影响系统方法设置导航条的title的forecolor

### ISSUE THREAD

**Issue by tanbinzone** [wangrui460/WRNavigationBar#41]
测试，在集成框架后，不能通过原始方法
    NSMutableDictionary *att = [NSMutableDictionary dictionary];
    att[NSFontAttributeName] = [UIFont systemFontOfSize:18];
    att[NSForegroundColorAttributeName] = UIColorFromRGB(0x00cccc);
    [appearance setTitleTextAttributes:att];
或者 [self.navigationController.navigationBar setTitleTextAttributes:@{NSFontAttributeName:[UIFont systemFontOfSize:20]}];
设置title的颜色，但是可以设置font。      找了好久原因。。。。。

**Comment by wangrui460** [comment]
[self wr_setNavBarTitleColor:[UIColor whiteColor]];
