### ISSUE TITLE
关于iOS11适配的问题

### ISSUE THREAD

**Issue by loveJuly** [wangrui460/WRNavigationBar#43]
跳转到地问个控制器之后，本来设置了进去导航栏透明度为0，在iOS11系统下已失效。

**Comment by songguolin** [comment]
还有iOS 11，iphone x下的导航栏高度有问题

**Comment by loveJuly** [comment]
楼主不更新了么。。。。

**Comment by zfx5130** [comment]
希望跟新一下，适配ios11..

**Comment by kzq5** [comment]
iphone x中状态栏问题，状态栏由20变成44了，所以要判断机型，是x的时候把static int kWRNavBarBottom = 64;改为static int kWRNavBarBottom = 88;

**Comment by shuiliang** [comment]
-(void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
    
//   self.automaticallyAdjustsScrollViewInsets = NO;

    if (@available(iOS 11.0, *)) {
        _collectionView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    } else {
        self.automaticallyAdjustsScrollViewInsets = NO;
    }
    
}


适配 iOS 11 的时候,首页的轮播图 图片在跳动 希望大神更新

**Comment by luo-h** [comment]
iOS11导航栏有很多问题，请更新一下

**Comment by huanglins** [comment]
参照作者的自己改了以下，增加了微信红包导航栏样式切换，适配了iOS11和 iPhone X。大家可以参考以下。
https://github.com/huanglins/VHLNavigation

**Comment by imqiuhang** [comment]
关于ios11 刚进来设置透明度为0实效适配问题  可以找到这个方法 修改下
- (void)BS_setBackgroundAlpha:(CGFloat)alpha {
    
    if (@available(iOS 11.0, *)) {
        [self BS_setBackgroundImage:[UIImage imageWithColor:[[UIColor whiteColor] colorWithAlphaComponent:alpha]]];
    }else {
        UIView *barBackgroundView = self.subviews.firstObject;
        barBackgroundView.alpha = alpha;
    }
}

**Comment by luo-h** [comment]
我在控制器的viewDidLoad中设置[self wr_setNavBarBackgroundAlpha:0];无用啊（不能透明）、但是通过scrollViewDidScroll代理又可以设置导航栏的颜色渐变

**Comment by AnyaWork** [comment]
希望楼主更新下iOS11 导航条问题。

**Comment by yangxiutao** [comment]
@luo-h 

- (void)wr_setBackgroundAlpha:(CGFloat)alpha
{
    if (@available (iOS 11, *)) {
        UIView *barBackgroundView = self.subviews.firstObject;
        barBackgroundView.alpha = alpha;
        [self backgroundView].alpha = alpha;
    }else{
        UIView *barBackgroundView = self.subviews.firstObject;
        barBackgroundView.alpha = alpha;
    }
}

**Comment by AnyaWork** [comment]
我试了，还是没有用，等你出新版本吧。iOS 11暂时，我做版本判断了。


原始邮件
发件人:SmileLifenotifications@github.com
收件人:wangrui460/WRNavigationBarWRNavigationBar@noreply.github.com
抄送:DeveloperWang858642232@qq.com; Commentcomment@noreply.github.com
发送时间:2017年9月23日(周六) 09:26
主题:Re: [wangrui460/WRNavigationBar] 关于iOS11适配的问题 (#43)


@luo-h
(void)wr_setBackgroundAlpha:(CGFloat)alpha
 {
 if (@available (iOS 11, *)) {
 UIView *barBackgroundView = self.subviews.firstObject;
 barBackgroundView.alpha = alpha;
 [self backgroundView].alpha = alpha;
 }else{
 UIView *barBackgroundView = self.subviews.firstObject;
 barBackgroundView.alpha = alpha;
 }
 }

**Comment by loveJuly** [comment]
关于iOS 11适配的问题，综合上面老哥的建议，结合本人遇到的bug，修改如下：
第一点：跳转界面之后会有导航栏高度的白色遮盖，修改建议：
- (void)wr_setBackgroundAlpha:(CGFloat)alpha
{
    if (@available (iOS 11, *)) {
        UIView *barBackgroundView = self.subviews.firstObject;
        barBackgroundView.alpha = alpha;
        [self backgroundView].alpha = alpha;
    }else{
        UIView *barBackgroundView = self.subviews.firstObject;
        barBackgroundView.alpha = alpha;
    }
}
ps:直接在WRNavigationBar.m文件搜索方法名修改即可。

第二点：适配iPhone X的高度
WRNavigationBar.m文件里面是用了static int kWRNavBarBottom = 64来处理的，因为iPhone X的导航栏高度变化问题，我的修改如下：
把static int kWRNavBarBottom = 64删掉，用如下宏定义替换：
#define Kinmo_ScreenWidth [UIScreen mainScreen].bounds.size.width
#define Kinmo_ScreenHeight [UIScreen mainScreen].bounds.size.height
#define Kinmo_iPhoneX (Kinmo_ScreenWidth == 375.f && Kinmo_ScreenHeight == 812.f ? YES : NO)
#define kWRNavBarBottom (Kinmo_iPhoneX ? 88.f : 64.f)

github上面的demo通过这两点修改后，经本人亲测，在iOS 11的手机以及iPhone X模拟器上均运行正常。

**Comment by luo-h** [comment]
楼上正解，主要就是导航栏的高度变化

**Comment by Rain-dew** [comment]
@loveJuly 兄弟，这改过后，导航栏最底部出现一条横线，一直弄不掉，但是上下滚动就没了，直接设置为0有个横线，这是怎么回事呢

**Comment by zzcshao** [comment]
大兄弟,导航栏最底部出现一条横线的bug解决了吗? @Rain-dew

**Comment by Rain-dew** [comment]
没有啊。不知道咋搞的，谁解决通知我下




Sent from Mail Master
在2017年09月26日 15:15，zzz 写道：

大兄弟,导航栏最底部出现一条横线的bug解决了吗? @Rain-dew

**Comment by loveJuly** [comment]
- (void)wr_setNavBarShadowImageHidden:(BOOL)hidden;
这个方法是隐藏导航栏底部的横线的。

**Comment by Rain-dew** [comment]
可以，很好，谢大哥




Sent from Mail Master
在2017年09月26日 15:18，kinmo 写道：
(void)wr_setNavBarShadowImageHidden:(BOOL)hidden;
这个方法是隐藏导航栏底部的横线的。

**Comment by weizhangCoder** [comment]
@ Rain-dew 为什么我写这个方法，还是有线 啊

**Comment by Doraemonyy** [comment]
@loveJuly 小哥费心了，666个赞给你！

**Comment by DonaldasZ** [comment]
pop回之后，导航栏不能滚动改变透明度了，有没有大佬遇到过，怎么解决的

**Comment by DonaldasZ** [comment]
ios11，pop回来，滚动改变不了导航栏透明度了，有没有大佬遇到过，怎么解决的
