### ISSUE TITLE
在常用中返回之后导航栏标题抖动

### ISSUE THREAD

**Issue by GUIYIVIEW** [wangrui460/WRNavigationBar#5]
侧滑一大部分距离后松开，可以看到返回时导航栏标题抖动了一下。

**Comment by GUIYIVIEW** [comment]
移动导航栏中，向上移动缩进导航栏，侧滑一部分距离，但是不返回，导航栏错位

**Comment by wangrui460** [comment]
你好，如果可以请将第一个问题录制一下发我邮箱wangruidev@gmail.com，或者加我qq 1204607318

**Comment by GUIYIVIEW** [comment]
你好，已发送邮箱

**Comment by wangrui460** [comment]
你好，感谢你提出issue，关于第一个问题，**是模拟器10.3的一个bug，在真机上是没有这种问题的**，之前也朋友提出这个问题，我也请他用真机测试了一下，确实不存在，所以你可以放心使用。关于第二个问题，我会抽时间尽快解决
![080c98cf-e6c4-415c-9b39-0c2d6815e008](https://user-images.githubusercontent.com/11909313/27268822-d02e6916-54e4-11e7-9dc4-df9a9fc8edeb.png)

**Comment by GUIYIVIEW** [comment]
好的，感谢

**Comment by wangrui460** [comment]
关于第二个移动导航栏错位的问题，已经初步解决提交了，现在正在优化滚动效果
