### ISSUE TITLE
给导航栏设置渐变色,底部内容透出来了, 除了第一种方法能解决吗?

### ISSUE THREAD

**Issue by xiaohange** [wangrui460/WRNavigationBar#60]
[self.navigationBar setBackgroundImage:navImg forBarMetrics:UIBarMetricsDefault];  
我是这么写的; 其中navImg是渐变色转的图片;   
除了self.navigationBar.translucent = NO; 解决方法;
你有别的解决方法吗? 
因为系统默认self.navigationBar.translucent = YES;
不想改动这个, 求好的建议谢谢!

**Comment by wangrui460** [comment]
系统给我们提供的 API 是最好的，只要不是 deprecated
