### ISSUE TITLE
更新适配iPhone X以后  导航条不能更改透明度

### ISSUE THREAD

**Issue by zhaoquntao** [wangrui460/WRNavigationBar#61]
[self wr_setNavBarBackgroundAlpha:0];
这句代码没用,不能设置导航条透明

**Comment by wangrui460** [comment]
具体看一下demo，如果是自定义导航栏，不能像以前那样使用了

**Comment by shuiliang** [comment]
我在首页里面这么写 [self wr_setNavBarBackgroundAlpha:0];也没有起到隐藏效果,我的导航栏不是自定义的,楼主demo 里 VC 都是 push 进去的,好像push那样设置 有起作用

**Comment by shuiliang** [comment]
一楼我弄好了,在WRNavigationBar.m里面这么改

- (void)wr_setBackgroundAlpha:(CGFloat)alpha
{

    if  ([WRNavigationBar isIphoneX]) {
        UIView *barBackgroundView = self.subviews.firstObject;
        barBackgroundView.alpha = alpha;
        [self backgroundView].alpha = alpha;
    }else{
        UIView *barBackgroundView = self.subviews.firstObject;
        barBackgroundView.alpha = alpha;
    }  
}

**Comment by shuiliang** [comment]
一楼我弄好了,在WRNavigationBar.m里面这么改

(void)wr_setBackgroundAlpha:(CGFloat)alpha
{

if (@available(iOS 11.0, *)) {
UIView *barBackgroundView = self.subviews.firstObject;
barBackgroundView.alpha = alpha;
[self backgroundView].alpha = alpha;
}else{
UIView *barBackgroundView = self.subviews.firstObject;
barBackgroundView.alpha = alpha;
}
}

**Comment by wangrui460** [comment]
刚更新了，你可以更新一下看看有没有解决你的问题
