### ISSUE TITLE
楼主，iOS 11 不用自定义导航栏还是有bug

### ISSUE THREAD

**Issue by VaeXnn** [wangrui460/WRNavigationBar#65]
具体描述如下：手势返回挪到中间然后又退回去，导航栏会显示出来，viewVillAppear 这个时机貌似没处理好

**Comment by wangrui460** [comment]
刚解决，你再看一下

**Comment by VaeXnn** [comment]
可以了，楼主大哥，我再测试一会，测测其他系统版本怎么样，然后有问题提给你，小问题say一个，导航栏透明的shdowImage还有黑线，不过手动设置也可以改，影响不大，谢谢楼主解决我的这个问题

**Comment by wangrui460** [comment]
导航栏透明的shdowImage还有黑线？

**Comment by VaeXnn** [comment]
[self wr_setNavBarBackgroundAlpha:0];
    [self wr_setNavBarShadowImageHidden:YES];初始化的时候得加上hidden这句话，因为源码里面的交换方法didAppear里面是通过[self wr_navBarShadowImageHidden]这个方法给shadowImage的，但是你只是设置alpla = 0.f，那个判断结果就为0，就会不隐藏，

**Comment by wangrui460** [comment]
我仔细看了一下demo，发现那条线确实没有隐藏。
后来发现我把 Demo 里面，AppDelegate文件中的统一设置底部黑线隐藏的方法给注释了~
日了🐶了，
实际库没有问题
