### ISSUE TITLE
发现个问题 只要导入这个库 系统的那些bartintcolor什么的都会无效 或者说不准确

### ISSUE THREAD

**Issue by dengxingwen** [wangrui460/WRNavigationBar#68]
发现个问题 只要导入这个库 系统的那些bartintcolor什么的都会无效 或者说不准确；只有删掉这个库 系统的那些例如self.navigationController.navigationBar setBarTintColor: 这个属性就错乱了 push之后 导航栏颜色就会变回去

**Comment by gj0134** [comment]
我也有这个bug ，使用这个库的方法设置tintcolor 很多时候会失效

**Comment by yeziahehe** [comment]
same question. When push and pop, system tintcolor setting will not be working.
