### ISSUE TITLE
lz，遇到一个问题就是知乎日报的那个demo

### ISSUE THREAD

**Issue by jaccty** [wangrui460/WRNavigationBar#69]
lz，遇到一个问题就是知乎日报的那个demo是正常的，向上滑动，导航栏会渐变显示，但是我调试了下我的demo，在WRNavigationBar.m的- (void)wr_setNavBarBackgroundAlpha:(CGFloat)alpha这个方法里
if ([self pushToCurrentVCFinished] == YES && [self pushToNextVCFinished] == NO) {
            NSLog(@"执行了pushToCurrentVCFinished");
            [self.navigationController setNeedsNavigationBarUpdateForBarBackgroundAlpha:alpha];
        }
不会进入这个if判断，是我少设置什么吗？麻烦解答下，多谢了。

**Comment by wangrui460** [comment]
你好，不知道显示是不是好的，你再试一下，如果还是不行的话，可以发个demo给我看一下，我会立马帮你解决
