### ISSUE TITLE
Demo里面知乎样式案例错位

### ISSUE THREAD

**Issue by huanglins** [wangrui460/WRNavigationBar#7]
![2017-06-18 1 22 01](https://user-images.githubusercontent.com/10528244/27258282-9d3d0d7a-5429-11e7-9fae-265f9c68c423.png)

如图。

还有导航栏中途终端，标题和导航栏文字不是从中断哪里开始，而是从最左边滑到中间来。

**Comment by wangrui460** [comment]
加一下我qq 1204607318，需要你描述一下具体情况，谢谢
