### ISSUE TITLE
ios11环境下api经常失效

### ISSUE THREAD

**Issue by gj0134** [wangrui460/WRNavigationBar#74]
[self wr_setNavBarBarTintColor:[UIColor colorWithHex:@"FFFFFF"]]；
[self wr_setNavBarTintColor:[UIColor blackColor]];
[self wr_setStatusBarStyle:UIStatusBarStyleLightContent];
目前发现这些方法有时候设置好了并未有效果。

**Comment by yeziahehe** [comment]
#68

**Comment by wangrui460** [comment]
刚更新了，你可以更新一下看看有没有解决你的问题
