### ISSUE TITLE
wr_setNavBarBackgroundAlpha not work

### ISSUE THREAD

**Issue by yeziahehe** [wangrui460/WRNavigationBar#76]
测试了一下，如果把 top constraint 设置为 superview.top 是 ok 的；
如果把 top constraint 设置为 safearea.top 该方法就无效了。

目前可以替代的方式把 top constraint 设置为 superview.top，且 content Insets = .never，这种情况是正常的。不过会出现 section header坐标 错位的问题是由 content Insets 引起，所以也不是完美替代方案。

最好的是适配 safe area 的情况下，将 top constraint 设置为 safearea.top，且 content Insets = .automatic。
不知道什么时候能够更新？这个问题优先级还是很高的。

**Comment by yeziahehe** [comment]
@wangrui460

**Comment by yeziahehe** [comment]
目前可以替代的方式把 top constraint 设置为 superview.top，且 content Insets = .never，这种情况是正常的。

**Comment by yeziahehe** [comment]
#73 #61

**Comment by wangrui460** [comment]
我在demo中，将NormalListController 的viewDidLoad 方法中的[self wr_setNavBarBackgroundAlpha:0];注释关了，页面正常显示，无法重现你们说的问题。
如果可以的话，我希望你们谁可以写个 有问题的demo发给我，我好debug~ 
谢谢了

**Comment by yeziahehe** [comment]
@wangrui460 [Demo 地址](https://github.com/yeziahehe/Demo)

1. 透明的问题，上面已经阐述过了。
2. storyboard 中设置的 nav 的属性，初次打开的时候没问题，一旦 push or pop 设置就无效了。

**Comment by wangrui460** [comment]
demo 里面什么都没有

**Comment by wangrui460** [comment]
[feadback](https://raw.githubusercontent.com/wangrui460/TemporaryStorage/master/feadback.png)

**Comment by wangrui460** [comment]
![feadback](https://raw.githubusercontent.com/wangrui460/TemporaryStorage/master/feadback.png)!

**Comment by yeziahehe** [comment]
你说的对，还是因为 iOS 11 safe area，top constraint 必须设置为 superview.top，否则 Tableview 的 x = 0 还是从nav下面开始计算。

但是storyboard 中设置的 nav 的属性，初次打开的时候没问题，一旦 push or pop 设置就无效了这个问题确实存在的。

**Comment by wangrui460** [comment]
暂时没有扩展 IB 上的功能，不过初次进入页面，api设置没有效果确实是一个问题，现在已经解决了，你可以更新一下看看

**Comment by yeziahehe** [comment]
我更新到 1.0.5 版本，IB 设置的属性完全失效了，且我并没有调用你的 api，你可以看看我的 demo。

**Comment by wangrui460** [comment]
上面说过了，暂不支持 IB，你IB设置失效是因为我设置了默认导航栏颜色

**Comment by quard8** [comment]
Same problem, but all demos works great. 

I see that method wr_setNavBarBackgroundAlpha is not calling updates, so condition is always FALSE

```objectivec
BOOL isRootViewController = (self.navigationController.viewControllers.firstObject == self);
if (([self pushToCurrentVCFinished] == YES || isRootViewController == YES) && [self pushToNextVCFinished] == NO) {
    [self.navigationController setNeedsNavigationBarUpdateForBarBackgroundAlpha:alpha];
}
```

**Comment by yeziahehe** [comment]
@quard8 i think you may use swift version... when i use lateset swift version, i have same problem.

**Comment by quard8** [comment]
@yeziahehe I'm using ObjC version :)

**Comment by yeziahehe** [comment]
@quard8 i am not the same question with you. I think may author can relay you later.

**Comment by wangrui460** [comment]
@quard8 

(([self pushToCurrentVCFinished] == YES || isRootViewController == YES) && [self pushToNextVCFinished] == NO) 

this condition always false?

**Comment by quard8** [comment]
@wangrui460 yeah!

**Comment by wangrui460** [comment]
@quard8 
([self pushToCurrentVCFinished] == YES || isRootViewController == YES)  FALSE
or
 [self pushToNextVCFinished] == NO  FALSE

**Comment by quard8** [comment]
This one:

````
([self pushToCurrentVCFinished] == YES || isRootViewController == YES) 
````

**Comment by wangrui460** [comment]
@quard8 
Can you give me a demo like the 5 floor?

**Comment by quard8** [comment]
Actually, I found the solution :) 

In method https://github.com/wangrui460/WRNavigationBar/blob/master/WRNavigationBar/WRNavigationBar.m#L491 I put completion block

````objectivec
[CATransaction setCompletionBlock:^{
        [displayLink invalidate];
        displayLink = nil;
        wrPushDisplayCount = 0;
        [viewController setPushToCurrentVCFinished:YES];
    }];
````

after ````[self wr_pushViewController:viewController animated:animated];```` and this did a trick.

I'm not sure why this works, but I know that completion block never called in this method :)

**Comment by wangrui460** [comment]
@quard8  
may be i know where the problem is?
i have update it, you can try again
