### ISSUE TITLE
在设置了NavBarBackgroundAlpha为0的controller中present新的controller的navbar总是闪

### ISSUE THREAD

**Issue by CNJXFCjack** [wangrui460/WRNavigationBar#77]
![gi3](https://user-images.githubusercontent.com/16531533/33160808-4e995b6c-d05a-11e7-8036-b7258b393159.gif)

问题如图

**Comment by xiaobeifeng** [comment]
我也是，你的问题解决了吗？

**Comment by CNJXFCjack** [comment]
@xiaobeifeng 尝试了在viewWillApperar中再次调用[self wr_setNavBarBarTintColor:COLOR]，貌似没问题。

**Comment by xiaobeifeng** [comment]
试了一下还是不行，依旧报错。
'NSInternalInconsistencyException', reason: 'Please file a radar on UIKit with this log if you see this assertion. selectorString = wr_setTitleTextAttributes:, exercisedImplementations = {
    "setBarTintColor:" =     (
    );
    "setTitleTextAttributes:" =     (
    );
    "setTranslucent:" =     (
    );
    "wr_setTitleTextAttributes:" =     (
    );
}’

使用Demo 中提供的方法，设置导航栏就不会报错，但是present时导航栏会闪一下，给用户的体验不好。。。。
// 设置导航栏默认的背景颜色
    [WRNavigationBar wr_setDefaultNavBarBarTintColor:MainNavBarColor];
    // 设置导航栏所有按钮的默认颜色
    [WRNavigationBar wr_setDefaultNavBarTintColor:[UIColor whiteColor]];
    // 设置导航栏标题默认颜色
    [WRNavigationBar wr_setDefaultNavBarTitleColor:[UIColor whiteColor]];
    // 统一设置状态栏样式
    [WRNavigationBar wr_setDefaultStatusBarStyle:UIStatusBarStyleLightContent];
    // 如果需要设置导航栏底部分割线隐藏，可以在这里统一设置
     [WRNavigationBar wr_setDefaultNavBarShadowImageHidden:YES];

在 2017年12月25日，下午3:48，Yijie <notifications@github.com<mailto:notifications@github.com>> 写道：


@xiaobeifeng<https://github.com/xiaobeifeng> 尝试了在viewWillApperar中再次调用[self wr_setNavBarBarTintColor:COLOR]，貌似没问题。

**Comment by CNJXFCjack** [comment]
报错我这边就不会了，具体的估计你得看源码了。
