### ISSUE TITLE
[self wr_setNavBarBarTintColor]问题

### ISSUE THREAD

**Issue by gj0134** [wangrui460/WRNavigationBar#79]
问题描述：
1、A页面pushB页面  A页面BarTintColor颜色为AColor，B页面BarTintColor颜色为BColor
发现的问题
1、在B页面通过侧滑回来的话，A页面BarTintColor颜色正常
2、在B页面通过点击返回按钮的话，A页面BarTintColor颜色不正常

如下图
![fullsizerender 3](https://user-images.githubusercontent.com/6159181/33200334-0ba3b55c-d12f-11e7-8b31-ef375f5e4b9b.jpg)
![fullsizerender 2](https://user-images.githubusercontent.com/6159181/33200335-0bd2b064-d12f-11e7-9809-661dc2fae36d.jpg)

**Comment by wangrui460** [comment]
两张图片看不出来有什么区别，最好发个Demo给我看看，我好帮你解决

**Comment by gj0134** [comment]
顶部bar颜色不一样，但是我这设置的颜色都是#333333
