### ISSUE TITLE
由左向右滑动返回上一级，手指滑动一半回退取消滑动，导航栏颜色变成白色了

### ISSUE THREAD

**Issue by xxjlovemoney** [wangrui460/WRNavigationBar#84]
楼主，帮解决下，由左向右滑动返回上一级，手指滑动一半回退向左取消滑动，导航栏颜色变成白色了

**Comment by wangrui460** [comment]
Demo 里面没有这个问题，你跟Demo对比一下看看，或者你加一下微信群，在群里面具体描述一下问题

**Comment by luo-h** [comment]
我是push到二级界面后导航栏就直接变成了白色，另一个项目是无论怎么设置导航栏都没用，一直是白色

**Comment by PoisonWang** [comment]
+1  解决了吗同学？
