### ISSUE TITLE
使用wr_setNavBarBackgroundAlpha改变透明度无效

### ISSUE THREAD

**Issue by HelloiWorld** [wangrui460/WRNavigationBar#86]
这几天使用这个库 发现有一个问题，做的很相似的页面，改变透明度发现一个有效，一个无效，
这里我两个界面只有跳转方法的区别，一个是 `[self.navigationController push...]`
还有一个是 通过全局的navi跳过去的，形如`[globalNavigationController push...]`
测试发现强制调用
`[self.navigationController setNeedsNavigationBarUpdateForBarBackgroundAlpha:alpha];` 才解决问题

进一步分析，就是

    [CATransaction setCompletionBlock:^{
        [displayLink invalidate];
        displayLink = nil;
        wrPushDisplayCount = 0;
        [viewController setPushToCurrentVCFinished:YES];
    }];
这一段代码有一种情况下没进block？所以`pushToCurrentVCFinished`的值总是NO，是否应该在 `wr_viewDidAppear`里面补上 `[self setPushToCurrentVCFinished:YES];`?

兼容Xcode 9以下版本，建议这样写

    // set _UIBarBackground alpha (_UIBarBackground subviews alpha <= _UIBarBackground alpha)
    - (void)wr_setBackgroundAlpha:(CGFloat)alpha
    {
        UIView *barBackgroundView = self.subviews.firstObject;
    #ifdef __IPHONE_11_0
        if (@available(iOS 11.0, *))
        {
            // sometimes we can't change _UIBarBackground alpha
            for (UIView *view in barBackgroundView.subviews) {
                 view.alpha = alpha;
             }
        } else {
    #endif
            barBackgroundView.alpha = alpha;
    #ifdef __IPHONE_11_0
        }
    #endif
    }

**Comment by wangrui460** [comment]
swift 版本写了，Objective-C的忘了~
