### ISSUE TITLE
prefersLargeTitles问题

### ISSUE THREAD

**Issue by nihaolifei999** [wangrui460/WRNavigationBar#88]
A对navigationBar没有设置任何内容，B仅设置了prefersLargeTitles
A-push > B, B的shadow没有了？ pop 会 A , A 此时也不显示shadow了

**Comment by ETHANAIR** [comment]
`self.navigationController.navigationBar.prefersLargeTitles = YES;`
这种情况下，WR对所有设置都失效了。
