### ISSUE TITLE
滑动手势:由左向右滑动.取消放开,有一定几率LeftBarItem消失

### ISSUE THREAD

**Issue by bijiasuo** [wangrui460/WRNavigationBar#89]
有人告诉我怎么解决么？
![wechatimg63](https://user-images.githubusercontent.com/16385556/34038029-cc5c4560-e1c5-11e7-9ab2-45c65a7011c7.jpeg)
![wechatimg64](https://user-images.githubusercontent.com/16385556/34038036-d67758be-e1c5-11e7-89c6-29d7aa08ce97.jpeg)

**Comment by libercata** [comment]
- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
试试把这个方法注了

**Comment by YNBand** [comment]
试了 注释 navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item { 方法，还是不好使啊

**Comment by libercata** [comment]
好使过吗？
会不会更新了pod，修改的代码被恢复了







------------------ 原始邮件 ------------------
发件人: "YNBand"<notifications@github.com>;
发送时间: 2018年5月16日(星期三) 下午3:42
收件人: "wangrui460/WRNavigationBar"<WRNavigationBar@noreply.github.com>;
抄送: "黄炜楠"<imhwn@vip.qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [wangrui460/WRNavigationBar] 滑动手势:由左向右滑动.取消放开,有一定几率LeftBarItem消失 (#89)




试了 注释 navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item { 方法，还是不好使啊
