### ISSUE TITLE
快速滑动返回，导航栏会有挺多bug

### ISSUE THREAD

**Issue by xylxi** [wangrui460/WRNavigationBar#9]
![image](https://user-images.githubusercontent.com/8691135/27333927-28ed318e-55fa-11e7-9fb7-88b25a71dafd.png)
![image](https://user-images.githubusercontent.com/8691135/27333936-2f2c451c-55fa-11e7-820e-c228d2f31be5.png)

**Comment by xylxi** [comment]
最新代码

**Comment by xylxi** [comment]
![image](https://user-images.githubusercontent.com/8691135/27334003-6c4e46e8-55fa-11e7-8b23-7ddfe285e3b2.png)
zhe真机调试不了，所以不知道真机上的表现如何

**Comment by wangrui460** [comment]
这是10.3模拟器的bug，在真机上没有问题，如果还有什么问题，请联系我
qq:1204607318
email:wangruidev@gmail.com
