### ISSUE TITLE
isBat判定为NO导致主界面导航栏设置未恢复的问题

### ISSUE THREAD

**Issue by HelloiWorld** [wangrui460/WRNavigationBar#90]
主界面有导航栏，已在AppDelegate里设置`[WRNavigationBar wr_setDefaultNavBarShadowImageHidden:NO];`
二级界面设置分割线隐藏`[self wr_setNavBarShadowImageHidden:YES];`
返回主界面，发现分割线被隐藏了，`[self isRootViewController]`的值为`YES`，`canUpdateNavigationBar`的值为`NO`

打印坐标如下

    viewFrame	CGRect	(origin = (x = 0, y = 0), size = (width = 375, height = 618))	
    maxFrame	CGRect	(origin = (x = 0, y = 0), size = (width = 375, height = 667))	
    middleFrame	CGRect	(origin = (x = 0, y = 64), size = (width = 375, height = 603))	
    minFrame	CGRect	(origin = (x = 0, y = 64), size = (width = 375, height = 554))	

所以导航栏没有恢复初始设置，蝙蝠🦇这里的判定无法满足所有情况

**Comment by HelloiWorld** [comment]
忘记说明了，是在主界面add了一个`childViewController`会出现此类情况

**Comment by wangrui460** [comment]
你好，我对此做过修改，你可以下载最新版本看一下是否还会出现这样的情况
