### ISSUE TITLE
右滑手势失效

### ISSUE THREAD

**Issue by WangXuanTong** [wangrui460/WRNavigationBar#92]
UIBarButtonItem *back_item = [[UIBarButtonItem alloc] initWithCustomView:button];
self.navigationItem.leftBarButtonItem = back_item;

当设置了leftBarButtonItem会导致右滑手势失效

**Comment by HelloiWorld** [comment]
讲道理，设置`leftBarButtonItem`后会隐藏系统默认的`backBarButtonItem`，所有手势失效，与这个项目无关
今天刚好处理了一个相关问题，设置`self.navigationItem.leftItemsSupplementBackButton = YES;` 
然后你可以对默认的`backBarButtonItem`作修改即可

**Comment by WangXuanTong** [comment]
self.navigationItem.leftItemsSupplementBackButton = YES;这样设置会导致我项目本身的左边按钮出现问题，这个不提。最终我是在我自己封装的UINavigationController中设置了self.interactivePopGestureRecognizer.delegate = nil;清空代理后，这样系统会重新设置，这样就解决了这个问题
