### ISSUE TITLE
关于点击输入框，导致NavigationBar错位的情况

### ISSUE THREAD

**Issue by onerain88** [wangrui460/WRNavigationBar#95]
首先，非常感谢这个库给开发带来的便利！
有一个奇怪的问题，当ViewController中包含输入框时，点击输入框会导致NavigationBar显示错位，如图
<img width="447" alt="wx20180102-113120 2x" src="https://user-images.githubusercontent.com/1450714/34473662-83316dc2-efb0-11e7-8d8c-1e82c198184a.png">

**Comment by yangxiutao** [comment]
解决了吗？
