### ISSUE TITLE
新建项目。有导航栏。pod进去后，导航栏直接变成纯白色了

### ISSUE THREAD

**Issue by Rain-dew** [wangrui460/WRNavigationBar#97]
pod 'WRNavigationBar','~>1.0.9’
什么代码都没写，导航栏颜色被改了。而且导航栏底部线条也没了

**Comment by wangrui460** [comment]
是这样的，目前加入了 “黑名单” 功能，可将不想改变的控制器加入 blackList 列表里。
“白名单” 功能待开发

**Comment by Rain-dew** [comment]
好的，抽空我试试，感谢




| |
邮箱：zhangyuluios@163.com
|

签名由 网易邮箱大师 定制

在2018年01月19日 21:11，wangrui460 写道：

是这样的，目前加入了 “黑名单” 功能，可将不想改变的控制器加入 blackList 列表里。
“白名单” 功能待开发
